[package]
name = "notification"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.13.0"
async-trait = "0.1.89"
sqlx = { version = "0.8.6", features = ["sqlite", "uuid"] }
uuid = "1.23.1"
actixutils = "0.1.2"
typed-eventbus = "0.2.1"
emailgrid = { git = "https://github.com/Austin-rgb/emailgrid" }
push = { git = "https://github.com/Austin-rgb/push" }
mgk = { git = "https://github.com/Austin-rgb/mgk" }
anyhow = "1.0.103"
serde = "1.0.228"
tracing = "0.1.44"
